# Site settings
title: ScottCreates.io
email: scott.q.tang@gmail.com
url: kidtango.github.io
baseurl: /scottcreates
description: 'Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description.'
keywords: 'your keywords, separated by commas'
skills: 'ABC: [Always] [Be] [Coding]'
meta_author: Tang Scott

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 375168 #80B3FF
  primary-rgb: '204,113,61' #"128,179,255"
  secondary: 26323d #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: ScottCreates.io
  # location: Location
  social: Around the Web
  # credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/scott-tang-a9b191142/
  - title: github
    url: http://github.com/kidtango

# Build settings
markdown: kramdown
permalink: pretty
